version: '3'

services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend

  web1:
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - backend

  web2:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge